# Generated by Django 4.2.1 on 2023-05-12 17:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_auth_tasks', '0003_alter_subtask_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 12, 8, 22, 870394)),
        ),
        migrations.CreateModel(
            name='MensajePrivado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=1000)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptor', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
