# Generated by Django 4.2.1 on 2023-05-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth_tasks', '0004_alter_subtask_created_at_mensajeprivado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='created_at',
            field=models.DateTimeField(default='12052023'),
        ),
    ]
