# Generated by Django 4.2.1 on 2023-05-12 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth_tasks', '0005_alter_subtask_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeprivado',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 14, 8, 3, 258483)),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 14, 8, 3, 258483)),
        ),
    ]
